services:
- type: web
  name: mystock
  env: python
  repo: https://github.com/johnliu123/mystock.git
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand:gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
